version: '2'
services:
  db:
    image: 'postgres:10.3-alpine'
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=delivery
      - POSTGRES_PASSWORD=delivery
      - POSTGRES_DB=delivery_boy_docker_development
      - PGDATA=/tmp
  queue:
    image: heidiks/rabbitmq-delayed-message-exchange
    environment:
      - RABBITMQ_DEFAULT_USER = guest
      - RABBITMQ_DEFAULT_PASS = guest
    ports:
      - "5672:5672"
      - "15672:15672"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@queue:5672
      - RACK_ENV=development_docker
      - RAILS_ENV=development_docker
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_HOST=queue
      - RABBIT_PORT=5672
      - DATABASE_PASSWORD=delivery
      - DATABASE_USERNAME=delivery
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - queue
  sneakers:
    build: .
    command: bash -c './waits-for queue:5672 -- bundle exec rake sneakers:run'
    environment:
      - RABBITMQ_URL=amqp://guest:guest@queue:5672
      - RACK_ENV=development_docker
      - RAILS_ENV=development_docker
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_HOST=queue
      - RABBIT_PORT=5672
      - DATABASE_PASSWORD=delivery
      - DATABASE_USERNAME=delivery
    volumes:
      - .:/myapp
    depends_on:
      - db
      - queue

volumes:
  postgres:
